/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ls.web.action.menu.petsale;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.ben.dao.petinfo.PetInfoDAO;
import com.ben.vo.petinfo.PetInfoVO;
import com.ls.model.user.RoleEntity;
import com.ls.web.service.pet.PetService;
import com.ls.web.service.player.RoleService;

/** 
 * MyEclipse Struts
 * Creation date: 09-01-2008
 * 
 * XDoclet definition:
 * @struts.action parameter="cmd" validate="true"
 * @struts.action-forward name="pet_list" path="/jsp/menu/petsale/pet_list.jsp"
 */
public class PetSaleAction extends DispatchAction
{
	/*
	 * Generated Methods
	 */

	Logger logger =  Logger.getLogger("log.action");
	/** 
	 * 宠物列表
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward n1(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		RoleService roleService = new RoleService();
		RoleEntity  roleInfo = roleService.getRoleInfoBySession(request.getSession());
		
		
		//UserTempBean userTempBean = (UserTempBean) request.getSession().getAttribute("userTempBean");

		int pPk = roleInfo.getBasicInfo().getPPk();
		int uPk = roleInfo.getBasicInfo().getUPk();
		
		//int menuId = Integer.valueOf((String) request.getAttribute("menu_id"));
		
		request.setAttribute("mapid", roleInfo.getBasicInfo().getSceneId()+"");
		
		//从角色身上取得宠物列表
		PetInfoDAO petInfoDAO = new PetInfoDAO();
		List<PetInfoVO> pet_list = petInfoDAO.getPetInfoList(pPk+"");
		
		logger.info("身上宠物数量"+pet_list.size());
		
		request.setAttribute("pet_list",pet_list);

		return mapping.findForward("pet_list");
	}	
	
	//卖出宠物
	public ActionForward n2(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		RoleService roleService = new RoleService();
		RoleEntity  roleInfo = roleService.getRoleInfoBySession(request.getSession());
		int pPk = roleInfo.getBasicInfo().getPPk();
		
		String petPk = request.getParameter("petPk");
		
		
		PetInfoDAO petInfoDAO = new PetInfoDAO();
		PetInfoVO petvo = petInfoDAO.getPetInfoView(petPk);
		String hintString = "";
		
		if (petvo.getPetIsBring() != 0) {
			hintString = "此宠物的为出战状态,不能卖出!";
			request.setAttribute("hint", hintString);			
			return mapping.findForward("pet_sale_info");			
		}
		
		if (petvo.getPetLonge() == 0) {
			hintString = "此宠物的寿命为零,不能卖出!";
			request.setAttribute("hint", hintString);			
			return mapping.findForward("pet_sale_info");			
		}
		//角色卖出宠物
		PetService petService = new PetService();
		petService.petSale(pPk+"",petPk);
		
		hintString = "您以"+petvo.getPetSale() +"文的价格卖出了"+petvo.getPetName();		
		request.setAttribute("hint", hintString);
		
		return mapping.findForward("pet_sale_info");
	}
	
	//列出宠物详细信息
	public ActionForward n3(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
	{
		String petPk = request.getParameter("petPk");
		RoleService roleService = new RoleService();
		RoleEntity  roleInfo = roleService.getRoleInfoBySession(request.getSession());
		int pPk = roleInfo.getBasicInfo().getPPk();
		
		
		PetService petSerivce = new PetService();
		
		String resultWml = petSerivce.getPetDisplayWml(Integer.parseInt(petPk));
		
		request.setAttribute("petPk", petPk);
		request.setAttribute("pPk", pPk+"");
		request.setAttribute("resultWml", resultWml);
		return mapping.findForward("pet_info");
		
		
	}
		
}