/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ls.web.action.wrap.pet;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.ls.ben.vo.info.pet.PetInfoVO;
import com.ls.model.user.RoleEntity;
import com.ls.web.service.pet.PetService;
import com.ls.web.service.player.RoleService;

/** 
 * MyEclipse Struts
 * Creation date: 10-15-2008
 * 
 * XDoclet definition:
 * @struts.action parameter="cmd" validate="true"
 * @struts.action-forward name="init_pet_list" path="init_pet_list.jsp"
 * @struts.action-forward name="init_pet_info" path="pet_info"
 * @struts.action-forward name="pet_egg_info" path="pet_egg_info"
 */
public class PetAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * 被洗宠物的列表
	 */
	public ActionForward n1(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String pg_pk = (String)request.getAttribute("pg_pk");
		if( pg_pk==null )
		{
			pg_pk = request.getParameter("pg_pk");
		}
		
		RoleService roleService = new RoleService();
		RoleEntity roleInfo = roleService.getRoleInfoBySession(request.getSession());
		
		int p_pk = roleInfo.getBasicInfo().getPPk();
		
		PetService petSerivce = new PetService();
		
		List<PetInfoVO> pets = petSerivce.getInitPetList(p_pk);
		
		request.setAttribute("pg_pk", pg_pk);
		request.setAttribute("pets", pets);
		return mapping.findForward("init_pet_list");
	}
	
	/** 
	 * 被洗宠物的详细信息
	 */
	public ActionForward n2(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String pet_pk = request.getParameter("pet_pk");
		String pg_pk = request.getParameter("pg_pk");
		
		PetService petSerivce = new PetService();
		
		String resultWml = petSerivce.getPetDisplayWml(Integer.parseInt(pet_pk));
		
		request.setAttribute("pet_pk", pet_pk);
		request.setAttribute("pg_pk", pg_pk);
		request.setAttribute("resultWml", resultWml);
		return mapping.findForward("pet_info");
	}
	
	/** 
	 * 洗宠物
	 */
	public ActionForward n4(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String pet_pk = request.getParameter("pet_pk");
		String pg_pk = request.getParameter("pg_pk");
		
		PetService petSerivce = new PetService();
		String hint = petSerivce.initPetByProp(Integer.parseInt(pet_pk),Integer.parseInt(pg_pk));
		
		String resultWml = petSerivce.getPetDisplayWml(Integer.parseInt(pet_pk));
		
		
		request.setAttribute("hint",hint );
		request.setAttribute("resultWml", resultWml);
		return mapping.findForward("init_pet_info");
	}
	
	
	/** 
	 * 宠物蛋生成的宠物详细信息
	 */
	public ActionForward n3(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String pet_pk = request.getParameter("pet_pk");
		
		PetService petSerivce = new PetService();
		
		String resultWml = petSerivce.getPetDisplayWml(Integer.parseInt(pet_pk));
		
		request.setAttribute("resultWml", resultWml);
		return mapping.findForward("pet_egg_info");
	}
	
	
	
}