/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ls.web.action.bill;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.ls.model.user.RoleEntity;
import com.ls.pub.constant.Channel;
import com.ls.web.service.player.RoleService;

/** 
 * MyEclipse Struts
 * Creation date: 05-13-2009
 * HHJ
 * XDoclet definition:
 * @struts.action parameter="cmd" validate="true"
 * @struts.action-forward name="bill_index" path="a"
 */
public class BillAction extends DispatchAction {
	 
	/**
	 * 充值渠道判定并转发不同的充值页面
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward n1(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		HttpSession new_session=request.getSession(); 
		
		RoleService roleService = new RoleService();
		RoleEntity roleInfo = roleService.getRoleInfoBySession(new_session);
		String lid = (String)request.getSession().getAttribute("lid");
		if(lid != null){
			if(Channel.TOM == Integer.parseInt(lid)){//是TOM的充值通道
				return mapping.findForward("tompage");
			}else{
				return mapping.findForward("nottompage");
			}
		} 
		return mapping.findForward("nottompage");
	}
}